import type { Section, ArticleMetaItem, AppStats, VerbTable } from './types'

export const ARTICLES_DATA = [
  { word: "Mann", translation: "homme", answer: "der" },
  { word: "Frau", translation: "femme", answer: "die" },
  { word: "Kind", translation: "enfant", answer: "das" },
  { word: "Hund", translation: "chien", answer: "der" },
  { word: "Katze", translation: "chat", answer: "die" },
  { word: "Haus", translation: "maison", answer: "das" },
  { word: "Auto", translation: "voiture", answer: "das" },
  { word: "Buch", translation: "livre", answer: "das" },
  { word: "Tisch", translation: "table", answer: "der" },
  { word: "Stuhl", translation: "chaise", answer: "der" },
  { word: "Tür", translation: "porte", answer: "die" },
  { word: "Fenster", translation: "fenêtre", answer: "das" },
  { word: "Schule", translation: "école", answer: "die" },
  { word: "Stadt", translation: "ville", answer: "die" },
  { word: "Bett", translation: "lit", answer: "das" },
  { word: "Apfel", translation: "pomme", answer: "der" },
  { word: "Milch", translation: "lait", answer: "die" },
  { word: "Wasser", translation: "eau", answer: "das" },
  { word: "Brot", translation: "pain", answer: "das" },
  { word: "Kaffee", translation: "café", answer: "der" },
  { word: "Tee", translation: "thé", answer: "der" },
  { word: "Käse", translation: "fromage", answer: "der" },
  { word: "Suppe", translation: "soupe", answer: "die" },
  { word: "Kuchen", translation: "gâteau", answer: "der" },
  { word: "Banane", translation: "banane", answer: "die" },
  { word: "Tomate", translation: "tomate", answer: "die" },
  { word: "Ei", translation: "œuf", answer: "das" },
  { word: "Glas", translation: "verre", answer: "das" },
  { word: "Handy", translation: "téléphone portable", answer: "das" },
  { word: "Fahrrad", translation: "vélo", answer: "das" },
  { word: "Theater", translation: "théâtre", answer: "das" },
  { word: "Brücke", translation: "pont", answer: "die" },
  { word: "Hafen", translation: "port", answer: "der" },
  { word: "Turm", translation: "tour", answer: "der" },
  { word: "Konzerthaus", translation: "salle de concert", answer: "das" },
  { word: "Moschee", translation: "mosquée", answer: "die" },
  { word: "Rathaus", translation: "mairie", answer: "das" },
  { word: "Bus", translation: "bus", answer: "der" },
  { word: "Zug", translation: "train", answer: "der" },
  { word: "Schlüssel", translation: "clé", answer: "der" },
  { word: "Tasche", translation: "sac", answer: "die" },
  { word: "Uhr", translation: "montre / horloge", answer: "die" },
  { word: "Lampe", translation: "lampe", answer: "die" },
  { word: "Blume", translation: "fleur", answer: "die" },
  { word: "Baum", translation: "arbre", answer: "der" },
  { word: "Zimmer", translation: "chambre / pièce", answer: "das" },
  { word: "Foto", translation: "photo", answer: "das" },
  { word: "Kopf", translation: "tête", answer: "der" },
  { word: "Auge", translation: "œil", answer: "das" },
  { word: "Ohr", translation: "oreille", answer: "das" },
  { word: "Nase", translation: "nez", answer: "die" },
  { word: "Mund", translation: "bouche", answer: "der" },
  { word: "Arm", translation: "bras", answer: "der" },
  { word: "Bein", translation: "jambe", answer: "das" },
  { word: "Fuß", translation: "pied", answer: "der" },
  { word: "Hand", translation: "main", answer: "die" },
  { word: "Finger", translation: "doigt", answer: "der" },
  { word: "Bauch", translation: "ventre", answer: "der" },
  { word: "Gesicht", translation: "visage", answer: "das" },
  { word: "Haar", translation: "cheveu / cheveux", answer: "das" },
  { word: "Hals", translation: "cou / gorge", answer: "der" },
  { word: "Rücken", translation: "dos", answer: "der" },
  { word: "Knie", translation: "genou", answer: "das" },
  { word: "Mutter", translation: "mère", answer: "die" },
  { word: "Vater", translation: "père", answer: "der" },
  { word: "Schwester", translation: "sœur", answer: "die" },
  { word: "Bruder", translation: "frère", answer: "der" },
  { word: "Tochter", translation: "fille (enfant)", answer: "die" },
  { word: "Sohn", translation: "fils", answer: "der" },
  { word: "Oma", translation: "grand-mère", answer: "die" },
  { word: "Opa", translation: "grand-père", answer: "der" },
  { word: "Baby", translation: "bébé", answer: "das" },
  { word: "Familie", translation: "famille", answer: "die" },
  { word: "Jacke", translation: "veste / blouson", answer: "die" },
  { word: "Hemd", translation: "chemise", answer: "das" },
  { word: "Hose", translation: "pantalon", answer: "die" },
  { word: "Kleid", translation: "robe", answer: "das" },
  { word: "Schuh", translation: "chaussure", answer: "der" },
  { word: "Socke", translation: "chaussette", answer: "die" },
  { word: "Mantel", translation: "manteau", answer: "der" },
  { word: "Mütze", translation: "bonnet / chapeau", answer: "die" },
  { word: "Pullover", translation: "pull", answer: "der" },
  { word: "Kartoffel", translation: "pomme de terre", answer: "die" },
  { word: "Fisch", translation: "poisson", answer: "der" },
  { word: "Salat", translation: "salade", answer: "der" },
  { word: "Nudel", translation: "pâte (alimentaire)", answer: "die" },
  { word: "Orange", translation: "orange", answer: "die" },
  { word: "Eis", translation: "glace / glace à l'eau", answer: "das" },
  { word: "Saft", translation: "jus", answer: "der" },
  { word: "Bier", translation: "bière", answer: "das" },
  { word: "Wein", translation: "vin", answer: "der" },
  { word: "Zucker", translation: "sucre", answer: "der" },
  { word: "Frühstück", translation: "petit-déjeuner", answer: "das" },
  { word: "Mittagessen", translation: "déjeuner", answer: "das" },
  { word: "Abendessen", translation: "dîner", answer: "das" },
  { word: "Küche", translation: "cuisine (pièce)", answer: "die" },
  { word: "Wohnzimmer", translation: "salon", answer: "das" },
  { word: "Badezimmer", translation: "salle de bain", answer: "das" },
  { word: "Wohnung", translation: "appartement", answer: "die" },
  { word: "Garten", translation: "jardin", answer: "der" },
  { word: "Schrank", translation: "armoire / placard", answer: "der" },
  { word: "Regal", translation: "étagère", answer: "das" },
  { word: "Kühlschrank", translation: "réfrigérateur", answer: "der" },
  { word: "Sofa", translation: "canapé", answer: "das" },
  { word: "Teppich", translation: "tapis", answer: "der" },
  { word: "Toilette", translation: "toilettes", answer: "die" },
  { word: "Wand", translation: "mur", answer: "die" },
  { word: "Boden", translation: "sol / plancher", answer: "der" },
  { word: "Berg", translation: "montagne", answer: "der" },
  { word: "Fluss", translation: "fleuve / rivière", answer: "der" },
  { word: "Meer", translation: "mer", answer: "das" },
  { word: "See", translation: "lac", answer: "der" },
  { word: "Wald", translation: "forêt", answer: "der" },
  { word: "Krankenhaus", translation: "hôpital", answer: "das" },
  { word: "Apotheke", translation: "pharmacie", answer: "die" },
  { word: "Supermarkt", translation: "supermarché", answer: "der" },
  { word: "Restaurant", translation: "restaurant", answer: "das" },
  { word: "Hotel", translation: "hôtel", answer: "das" },
  { word: "Bahnhof", translation: "gare", answer: "der" },
  { word: "Flughafen", translation: "aéroport", answer: "der" },
  { word: "Kino", translation: "cinéma", answer: "das" },
  { word: "Bibliothek", translation: "bibliothèque", answer: "die" },
  { word: "Büro", translation: "bureau", answer: "das" },
  { word: "Park", translation: "parc", answer: "der" },
  { word: "Kirche", translation: "église", answer: "die" },
  { word: "Markt", translation: "marché", answer: "der" },
  { word: "Flugzeug", translation: "avion", answer: "das" },
  { word: "Schiff", translation: "bateau / navire", answer: "das" },
  { word: "U-Bahn", translation: "métro", answer: "die" },
  { word: "Straßenbahn", translation: "tramway", answer: "die" },
  { word: "Taxi", translation: "taxi", answer: "das" },
  { word: "Roller", translation: "scooter / trottinette", answer: "der" },
  { word: "Fähre", translation: "ferry", answer: "die" },
  { word: "Haltestelle", translation: "arrêt (bus/tram)", answer: "die" },
  { word: "Gleis", translation: "voie / quai", answer: "das" },
  { word: "Bahnsteig", translation: "quai (gare)", answer: "der" },
  { word: "Ticket", translation: "billet / ticket", answer: "das" },
  { word: "Abfahrt", translation: "départ", answer: "die" },
  { word: "Ankunft", translation: "arrivée", answer: "die" },
  { word: "Motorrad", translation: "moto", answer: "das" },
  { word: "Koffer", translation: "valise", answer: "der" },
  { word: "Stunde", translation: "heure", answer: "die" },
  { word: "Minute", translation: "minute", answer: "die" },
  { word: "Tag", translation: "jour", answer: "der" },
  { word: "Woche", translation: "semaine", answer: "die" },
  { word: "Monat", translation: "mois", answer: "der" },
  { word: "Jahr", translation: "année", answer: "das" },
  { word: "Nacht", translation: "nuit", answer: "die" },
  { word: "Morgen", translation: "matin", answer: "der" },
  { word: "Abend", translation: "soir", answer: "der" },
  { word: "Beruf", translation: "métier / profession", answer: "der" },
  { word: "Geld", translation: "argent", answer: "das" },
  { word: "Sprache", translation: "langue", answer: "die" },
  { word: "Wort", translation: "mot", answer: "das" },
  { word: "Frage", translation: "question", answer: "die" },
  { word: "Antwort", translation: "réponse", answer: "die" },
  { word: "Brief", translation: "lettre (courrier)", answer: "der" },
  { word: "Zeitung", translation: "journal (presse)", answer: "die" },
  { word: "Heft", translation: "cahier", answer: "das" },
  { word: "Stift", translation: "stylo / crayon", answer: "der" },
  { word: "Tier", translation: "animal", answer: "das" },
  { word: "Vogel", translation: "oiseau", answer: "der" },
  { word: "Pferd", translation: "cheval", answer: "das" },
  { word: "Kuh", translation: "vache", answer: "die" },
  { word: "Schwein", translation: "cochon / porc", answer: "das" },
  { word: "Sonne", translation: "soleil", answer: "die" },
  { word: "Mond", translation: "lune", answer: "der" },
  { word: "Stern", translation: "étoile", answer: "der" },
  { word: "Regen", translation: "pluie", answer: "der" },
  { word: "Schnee", translation: "neige", answer: "der" },
  { word: "Wolke", translation: "nuage", answer: "die" },
  { word: "Wind", translation: "vent", answer: "der" },
];

export const COUNTRIES_DATA = [
  { word: "Deutschland", translation: "Allemagne", answer: "aucun" },
  { word: "Frankreich", translation: "France", answer: "aucun" },
  { word: "Italien", translation: "Italie", answer: "aucun" },
  { word: "Spanien", translation: "Espagne", answer: "aucun" },
  { word: "Japan", translation: "Japon", answer: "aucun" },
  { word: "China", translation: "Chine", answer: "aucun" },
  { word: "Russland", translation: "Russie", answer: "aucun" },
  { word: "Brasilien", translation: "Brésil", answer: "aucun" },
  { word: "Australien", translation: "Australie", answer: "aucun" },
  { word: "Österreich", translation: "Autriche", answer: "aucun" },
  { word: "Polen", translation: "Pologne", answer: "aucun" },
  { word: "Kanada", translation: "Canada", answer: "aucun" },
  { word: "Portugal", translation: "Portugal", answer: "aucun" },
  { word: "Schweden", translation: "Suède", answer: "aucun" },
  { word: "Belgien", translation: "Belgique", answer: "aucun" },
  { word: "Ungarn", translation: "Hongrie", answer: "aucun" },
  { word: "Schweiz", translation: "Suisse", answer: "der" },
  { word: "Türkei", translation: "Turquie", answer: "der" },
  { word: "Slowakei", translation: "Slovaquie", answer: "der" },
  { word: "Mongolei", translation: "Mongolie", answer: "der" },
  { word: "Iran", translation: "Iran", answer: "dem" },
  { word: "Irak", translation: "Irak", answer: "dem" },
  { word: "Sudan", translation: "Soudan", answer: "dem" },
  { word: "Libanon", translation: "Liban", answer: "dem" },
  { word: "Jemen", translation: "Yémen", answer: "dem" },
  { word: "Senegal", translation: "Sénégal", answer: "dem" },
  { word: "Kongo", translation: "Congo", answer: "dem" },
  { word: "USA", translation: "États-Unis", answer: "den" },
  { word: "Niederlande", translation: "Pays-Bas", answer: "den" },
  { word: "Philippinen", translation: "Philippines", answer: "den" },
];

export const VERBS_DATA = [
  { infinitive: "sein",     pronoun: "ich",       translation: "être",       answer: "bin"    },
  { infinitive: "sein",     pronoun: "du",        translation: "être",       answer: "bist"   },
  { infinitive: "sein",     pronoun: "er/sie/es", translation: "être",       answer: "ist"    },
  { infinitive: "sein",     pronoun: "wir",       translation: "être",       answer: "sind"   },
  { infinitive: "sein",     pronoun: "ihr",       translation: "être",       answer: "seid"   },
  { infinitive: "haben",    pronoun: "du",        translation: "avoir",      answer: "hast"   },
  { infinitive: "haben",    pronoun: "er/sie/es", translation: "avoir",      answer: "hat"    },
  { infinitive: "fahren",   pronoun: "er/sie/es", translation: "conduire",   answer: "fährt"  },
  { infinitive: "schlafen", pronoun: "er/sie/es", translation: "dormir",     answer: "schläft"},
  { infinitive: "lesen",    pronoun: "er/sie/es", translation: "lire",       answer: "liest"  },
  { infinitive: "sehen",    pronoun: "er/sie/es", translation: "voir",       answer: "sieht"  },
  { infinitive: "nehmen",   pronoun: "er/sie/es", translation: "prendre",    answer: "nimmt"  },
  { infinitive: "sprechen", pronoun: "er/sie/es", translation: "parler",     answer: "spricht"},
  { infinitive: "essen",    pronoun: "er/sie/es", translation: "manger",     answer: "isst"   },
  { infinitive: "geben",    pronoun: "er/sie/es", translation: "donner",     answer: "gibt"   },
  { infinitive: "helfen",   pronoun: "er/sie/es", translation: "aider",      answer: "hilft"  },
  { infinitive: "laufen",   pronoun: "er/sie/es", translation: "courir",     answer: "läuft"  },
  { infinitive: "treffen",  pronoun: "er/sie/es", translation: "rencontrer", answer: "trifft" },
  { infinitive: "wissen",   pronoun: "er/sie/es", translation: "savoir",     answer: "weiß"   },
  { infinitive: "werden",   pronoun: "er/sie/es", translation: "devenir",    answer: "wird"   },
];

export const PLURALS_DATA = [
  { singular: "Mann", article: "der", translation: "homme", answer: "Männer", wrong: ["Mannen","Männen","Mans"] },
  { singular: "Frau", article: "die", translation: "femme", answer: "Frauen", wrong: ["Fraue","Fraus","Fraüen"] },
  { singular: "Kind", article: "das", translation: "enfant", answer: "Kinder", wrong: ["Kinds","Kindes","Kinde"] },
  { singular: "Hund", article: "der", translation: "chien", answer: "Hunde", wrong: ["Hunden","Hunds","Hünde"] },
  { singular: "Katze", article: "die", translation: "chat", answer: "Katzen", wrong: ["Katzes","Katzs","Kätzten"] },
  { singular: "Haus", article: "das", translation: "maison", answer: "Häuser", wrong: ["Hauser","Hauses","Häuse"] },
  { singular: "Auto", article: "das", translation: "voiture", answer: "Autos", wrong: ["Aute","Autoen","Äutos"] },
  { singular: "Buch", article: "das", translation: "livre", answer: "Bücher", wrong: ["Buchs","Buchen","Büchen"] },
  { singular: "Tisch", article: "der", translation: "table", answer: "Tische", wrong: ["Tischen","Tischs","Tischse"] },
  { singular: "Stuhl", article: "der", translation: "chaise", answer: "Stühle", wrong: ["Stuhl","Stuhle","Stühl"] },
  { singular: "Tür", article: "die", translation: "porte", answer: "Türen", wrong: ["Türe","Türs","Tüer"] },
  { singular: "Fenster", article: "das", translation: "fenêtre", answer: "Fenster", wrong: ["Fenstern","Fensters","Fenstere"] },
  { singular: "Schule", article: "die", translation: "école", answer: "Schulen", wrong: ["Schules","Schuls","Schülen"] },
  { singular: "Stadt", article: "die", translation: "ville", answer: "Städte", wrong: ["Städten","Stadts","Stadte"] },
  { singular: "Bett", article: "das", translation: "lit", answer: "Betten", wrong: ["Bette","Bettn","Bets"] },
  { singular: "Apfel", article: "der", translation: "pomme", answer: "Äpfel", wrong: ["Apfels","Apfeln","Äpfeln"] },
  { singular: "Wasser", article: "das", translation: "eau", answer: "Wässer", wrong: ["Wassers","Wassern","Wasser"] },
  { singular: "Brot", article: "das", translation: "pain", answer: "Brote", wrong: ["Broten","Brots","Bröte"] },
  { singular: "Kaffee", article: "der", translation: "café", answer: "Kaffees", wrong: ["Kaffe","Kaffeen","Käffee"] },
  { singular: "Tee", article: "der", translation: "thé", answer: "Tees", wrong: ["Teen","Tee","Töe"] },
  { singular: "Käse", article: "der", translation: "fromage", answer: "Käse", wrong: ["Käsen","Käses","Käsee"] },
  { singular: "Suppe", article: "die", translation: "soupe", answer: "Suppen", wrong: ["Suppes","Supps","Süppen"] },
  { singular: "Kuchen", article: "der", translation: "gâteau", answer: "Kuchen", wrong: ["Kuchens","Küchen","Kuchene"] },
  { singular: "Banane", article: "die", translation: "banane", answer: "Bananen", wrong: ["Bananes","Banans","Bananene"] },
  { singular: "Tomate", article: "die", translation: "tomate", answer: "Tomaten", wrong: ["Tomates","Tomats","Tomatene"] },
  { singular: "Ei", article: "das", translation: "œuf", answer: "Eier", wrong: ["Eie","Eis","Eien"] },
  { singular: "Glas", article: "das", translation: "verre", answer: "Gläser", wrong: ["Glaser","Glases","Gläse"] },
  { singular: "Handy", article: "das", translation: "téléphone portable", answer: "Handys", wrong: ["Handies","Handie","Händys"] },
  { singular: "Straßenbahn", article: "die", translation: "tramway", answer: "Straßenbahnen", wrong: ["Straßenbahns", "Straßenbahne", "Straßenbähnen"] },
  { singular: "Taxi", article: "das", translation: "taxi", answer: "Taxis", wrong: ["Taxen", "Taxie", "Täxis"] },
  { singular: "Roller", article: "der", translation: "scooter", answer: "Roller", wrong: ["Rollern", "Rollers", "Röller"] },
  { singular: "Fähre", article: "die", translation: "ferry", answer: "Fähren", wrong: ["Fähres", "Fährs", "Fahren"] },
  { singular: "Fahrrad", article: "das", translation: "vélo", answer: "Fahrräder", wrong: ["Fahrrads", "Fahrrade", "Fahrräden"] },
  { singular: "Haltestelle", article: "die", translation: "arrêt", answer: "Haltestellen", wrong: ["Haltestelles", "Haltestelln", "Haltestele"] },
  { singular: "Gleis", article: "das", translation: "voie / quai", answer: "Gleise", wrong: ["Gleis", "Gleisen", "Gläise"] },
  { singular: "Bahnsteig", article: "der", translation: "quai", answer: "Bahnsteige", wrong: ["Bahnsteigs", "Bahnsteigen", "Bahnstöige"] },
  { singular: "Ticket", article: "das", translation: "billet", answer: "Tickets", wrong: ["Tickete", "Ticketen", "Tückets"] },
  { singular: "Abfahrt", article: "die", translation: "départ", answer: "Abfahrten", wrong: ["Abfahrts", "Abfahrte", "Abfährten"] },
  { singular: "Ankunft", article: "die", translation: "arrivée", answer: "Ankünfte", wrong: ["Ankunfts", "Ankunfte", "Ankunften"] },
  { singular: "Bus", article: "der", translation: "bus", answer: "Busse", wrong: ["Busen","Buse","Büsse"] },
  { singular: "Zug", article: "der", translation: "train", answer: "Züge", wrong: ["Zuge","Zugen","Zugs"] },
  { singular: "Theater", article: "das", translation: "théâtre", answer: "Theater", wrong: ["Theaters", "Theatere", "Theäter"] },
  { singular: "Brücke", article: "die", translation: "pont", answer: "Brücken", wrong: ["Brückes", "Brückens", "Brücken"] },
  { singular: "Hafen", article: "der", translation: "port", answer: "Häfen", wrong: ["Hafens", "Hafen", "Hafene"] },
  { singular: "Turm", article: "der", translation: "tour", answer: "Türme", wrong: ["Turms", "Turmе", "Türmen"] },
  { singular: "Konzerthaus", article: "das", translation: "salle de concert", answer: "Konzerthäuser", wrong: ["Konzerthauser", "Konzerthause", "Konzerthäusern"] },
  { singular: "Moschee", article: "die", translation: "mosquée", answer: "Moscheen", wrong: ["Moschees", "Moscheen", "Möscheen"] },
  { singular: "Rathaus", article: "das", translation: "mairie", answer: "Rathäuser", wrong: ["Rathauser", "Rathause", "Rathäusern"] },
  { singular: "Schlüssel", article: "der", translation: "clé", answer: "Schlüssel", wrong: ["Schlüsseln","Schlüssels","Schlüssele"] },
  { singular: "Tasche", article: "die", translation: "sac", answer: "Taschen", wrong: ["Tasches","Taschs","Täschen"] },

  { singular: "Uhr", article: "die", translation: "montre / horloge", answer: "Uhren", wrong: ["Uhre","Uhrs","Ühr"] },
  { singular: "Lampe", article: "die", translation: "lampe", answer: "Lampen", wrong: ["Lampes","Lamps","Lämpten"] },
  { singular: "Blume", article: "die", translation: "fleur", answer: "Blumen", wrong: ["Blumes","Blums","Blümens"] },
  { singular: "Baum", article: "der", translation: "arbre", answer: "Bäume", wrong: ["Baums","Baumen","Bäumen"] },
  { singular: "Zimmer", article: "das", translation: "chambre / pièce", answer: "Zimmer", wrong: ["Zimmern","Zimmers","Zimmere"] },
  { singular: "Foto", article: "das", translation: "photo", answer: "Fotos", wrong: ["Fote","Foten","Fötos"] },
  { singular: "Kopf", article: "der", translation: "tête", answer: "Köpfe", wrong: ["Kopfs","Kopfen","Köpfen"] },
  { singular: "Auge", article: "das", translation: "œil", answer: "Augen", wrong: ["Auges","Augn","Äugen"] },
  { singular: "Ohr", article: "das", translation: "oreille", answer: "Ohren", wrong: ["Ohre","Ohrs","Öhren"] },
  { singular: "Nase", article: "die", translation: "nez", answer: "Nasen", wrong: ["Nases","Nass","Näsen"] },
  { singular: "Mund", article: "der", translation: "bouche", answer: "Münder", wrong: ["Munde","Munds","Münde"] },
  { singular: "Arm", article: "der", translation: "bras", answer: "Arme", wrong: ["Armen","Arms","Ärme"] },
  { singular: "Bein", article: "das", translation: "jambe", answer: "Beine", wrong: ["Beins","Beinen","Böine"] },
  { singular: "Fuß", article: "der", translation: "pied", answer: "Füße", wrong: ["Fuss","Fußen","Fuße"] },
  { singular: "Hand", article: "die", translation: "main", answer: "Hände", wrong: ["Hands","Handen","Hande"] },
  { singular: "Finger", article: "der", translation: "doigt", answer: "Finger", wrong: ["Fingern","Fingers","Fingere"] },
  { singular: "Bauch", article: "der", translation: "ventre", answer: "Bäuche", wrong: ["Bauchs","Bauchen","Bauchi"] },
  { singular: "Gesicht", article: "das", translation: "visage", answer: "Gesichter", wrong: ["Gesichts","Gesichte","Gesichten"] },
  { singular: "Haar", article: "das", translation: "cheveu", answer: "Haare", wrong: ["Haars","Haaren","Häare"] },
  { singular: "Hals", article: "der", translation: "cou / gorge", answer: "Hälse", wrong: ["Halse","Halsen","Hals"] },
  { singular: "Rücken", article: "der", translation: "dos", answer: "Rücken", wrong: ["Rückens","Rückene","Rückenn"] },
  { singular: "Knie", article: "das", translation: "genou", answer: "Knie", wrong: ["Knien","Knies","Kniee"] },
  { singular: "Mutter", article: "die", translation: "mère", answer: "Mütter", wrong: ["Muttern","Mutters","Müttere"] },
  { singular: "Vater", article: "der", translation: "père", answer: "Väter", wrong: ["Vaters","Vatern","Vätern"] },
  { singular: "Schwester", article: "die", translation: "sœur", answer: "Schwestern", wrong: ["Schwestern","Schwestres","Schwesternn"] },
  { singular: "Bruder", article: "der", translation: "frère", answer: "Brüder", wrong: ["Bruders","Brudern","Brüdern"] },
  { singular: "Tochter", article: "die", translation: "fille (enfant)", answer: "Töchter", wrong: ["Tochtere","Tochters","Töchtern"] },
  { singular: "Sohn", article: "der", translation: "fils", answer: "Söhne", wrong: ["Sohne","Sohns","Söhnen"] },
  { singular: "Oma", article: "die", translation: "grand-mère", answer: "Omas", wrong: ["Omen","Ömas","Omae"] },
  { singular: "Opa", article: "der", translation: "grand-père", answer: "Opas", wrong: ["Open","Öpas","Opae"] },
  { singular: "Baby", article: "das", translation: "bébé", answer: "Babys", wrong: ["Babies","Babyes","Bäbys"] },
  { singular: "Familie", article: "die", translation: "famille", answer: "Familien", wrong: ["Familis","Familys","Familiene"] },
  { singular: "Jacke", article: "die", translation: "veste", answer: "Jacken", wrong: ["Jackes","Jacks","Jäcken"] },
  { singular: "Hemd", article: "das", translation: "chemise", answer: "Hemden", wrong: ["Hemds","Hemdes","Hämden"] },
  { singular: "Hose", article: "die", translation: "pantalon", answer: "Hosen", wrong: ["Hoses","Hoss","Hösen"] },
  { singular: "Kleid", article: "das", translation: "robe", answer: "Kleider", wrong: ["Kleids","Kleide","Kleiden"] },
  { singular: "Schuh", article: "der", translation: "chaussure", answer: "Schuhe", wrong: ["Schuhs","Schuen","Schühe"] },
  { singular: "Socke", article: "die", translation: "chaussette", answer: "Socken", wrong: ["Sockes","Socks","Söcken"] },
  { singular: "Mantel", article: "der", translation: "manteau", answer: "Mäntel", wrong: ["Mantels","Manteле","Mänteln"] },
  { singular: "Mütze", article: "die", translation: "bonnet", answer: "Mützen", wrong: ["Mützes","Mützs","Mutzen"] },
  { singular: "Pullover", article: "der", translation: "pull", answer: "Pullover", wrong: ["Pullovern","Pullovers","Pullövern"] },
  { singular: "Kartoffel", article: "die", translation: "pomme de terre", answer: "Kartoffeln", wrong: ["Kartoffels","Kartoffel","Kartofflen"] },
  { singular: "Fisch", article: "der", translation: "poisson", answer: "Fische", wrong: ["Fischs","Fischen","Füsche"] },
  { singular: "Salat", article: "der", translation: "salade", answer: "Salate", wrong: ["Salats","Salaten","Saläte"] },
  { singular: "Nudel", article: "die", translation: "pâte alimentaire", answer: "Nudeln", wrong: ["Nudeles","Nudels","Nüdeln"] },
  { singular: "Orange", article: "die", translation: "orange", answer: "Orangen", wrong: ["Oranges","Orangns","Örangen"] },
  { singular: "Saft", article: "der", translation: "jus", answer: "Säfte", wrong: ["Safts","Saftes","Safte"] },
  { singular: "Bier", article: "das", translation: "bière", answer: "Biere", wrong: ["Biers","Bieren","Böere"] },
  { singular: "Wein", article: "der", translation: "vin", answer: "Weine", wrong: ["Weins","Weinen","Wöine"] },
  { singular: "Frühstück", article: "das", translation: "petit-déjeuner", answer: "Frühstücke", wrong: ["Frühstücks","Frühstücken","Frühstücks"] },
  { singular: "Mittagessen", article: "das", translation: "déjeuner", answer: "Mittagessen", wrong: ["Mittagessens","Mittagessenen","Mittagessen"] },
  { singular: "Abendessen", article: "das", translation: "dîner", answer: "Abendessen", wrong: ["Abendessens","Abendesser","Abendessel"] },
  { singular: "Küche", article: "die", translation: "cuisine (pièce)", answer: "Küchen", wrong: ["Küches","Küchs","Kuchen"] },
  { singular: "Wohnzimmer", article: "das", translation: "salon", answer: "Wohnzimmer", wrong: ["Wohnzimmern","Wohnzimmers","Wohnzimmere"] },
  { singular: "Badezimmer", article: "das", translation: "salle de bain", answer: "Badezimmer", wrong: ["Badezimmern","Badezimmers","Badezimmere"] },
  { singular: "Wohnung", article: "die", translation: "appartement", answer: "Wohnungen", wrong: ["Wohnungs","Wohnung","Wohnunge"] },
  { singular: "Garten", article: "der", translation: "jardin", answer: "Gärten", wrong: ["Gartens","Garten","Gärte"] },
  { singular: "Schrank", article: "der", translation: "armoire", answer: "Schränke", wrong: ["Schranks","Schranken","Schrankе"] },
  { singular: "Regal", article: "das", translation: "étagère", answer: "Regale", wrong: ["Regals","Regaln","Régale"] },
  { singular: "Kühlschrank", article: "der", translation: "réfrigérateur", answer: "Kühlschränke", wrong: ["Kühlschranks","Kühlschranken","Kühlschränken"] },
  { singular: "Sofa", article: "das", translation: "canapé", answer: "Sofas", wrong: ["Sofae","Sofen","Söfas"] },
  { singular: "Teppich", article: "der", translation: "tapis", answer: "Teppiche", wrong: ["Teppichs","Teppichen","Töppiche"] },
  { singular: "Toilette", article: "die", translation: "toilettes", answer: "Toiletten", wrong: ["Toilettes","Toiletts","Toilleten"] },
  { singular: "Wand", article: "die", translation: "mur", answer: "Wände", wrong: ["Wands","Wanden","Wande"] },
  { singular: "Boden", article: "der", translation: "sol", answer: "Böden", wrong: ["Bodens","Boden","Bodene"] },
  { singular: "Berg", article: "der", translation: "montagne", answer: "Berge", wrong: ["Bergs","Bergen","Börge"] },
  { singular: "Fluss", article: "der", translation: "fleuve", answer: "Flüsse", wrong: ["Fluss","Flussen","Flusse"] },
  { singular: "Meer", article: "das", translation: "mer", answer: "Meere", wrong: ["Meers","Meeren","Möere"] },
  { singular: "See", article: "der", translation: "lac", answer: "Seen", wrong: ["Sees","See","Söen"] },
  { singular: "Wald", article: "der", translation: "forêt", answer: "Wälder", wrong: ["Walds","Walde","Walden"] },
  { singular: "Krankenhaus", article: "das", translation: "hôpital", answer: "Krankenhäuser", wrong: ["Krankenhäuse","Krankenhauser","Krankenhausern"] },
  { singular: "Apotheke", article: "die", translation: "pharmacie", answer: "Apotheken", wrong: ["Apothekens","Apothekes","Apothekene"] },
  { singular: "Supermarkt", article: "der", translation: "supermarché", answer: "Supermärkte", wrong: ["Supermarkts","Supermärken","Supermarkten"] },
  { singular: "Restaurant", article: "das", translation: "restaurant", answer: "Restaurants", wrong: ["Restaurante","Restoranten","Restaurantn"] },
  { singular: "Hotel", article: "das", translation: "hôtel", answer: "Hotels", wrong: ["Hotele","Hotelen","Hötels"] },
  { singular: "Bahnhof", article: "der", translation: "gare", answer: "Bahnhöfe", wrong: ["Bahnhofs","Bahnhofen","Bahnhöfen"] },
  { singular: "Flughafen", article: "der", translation: "aéroport", answer: "Flughäfen", wrong: ["Flughafens","Flughafen","Flughafene"] },
  { singular: "Kino", article: "das", translation: "cinéma", answer: "Kinos", wrong: ["Kinoe","Kinoen","Kinös"] },
  { singular: "Bibliothek", article: "die", translation: "bibliothèque", answer: "Bibliotheken", wrong: ["Bibliotheks","Bibliothekens","Bibliotheke"] },
  { singular: "Büro", article: "das", translation: "bureau", answer: "Büros", wrong: ["Büroe","Büroen","Burós"] },
  { singular: "Park", article: "der", translation: "parc", answer: "Parks", wrong: ["Parke","Parken","Pärke"] },
  { singular: "Kirche", article: "die", translation: "église", answer: "Kirchen", wrong: ["Kirches","Kirchs","Kürchn"] },
  { singular: "Markt", article: "der", translation: "marché", answer: "Märkte", wrong: ["Markts","Markten","Märkten"] },
  { singular: "Flugzeug", article: "das", translation: "avion", answer: "Flugzeuge", wrong: ["Flugzeugs","Flugzeugen","Flugzügе"] },
  { singular: "Schiff", article: "das", translation: "bateau", answer: "Schiffe", wrong: ["Schiffs","Schiffen","Schifft"] },
  { singular: "U-Bahn", article: "die", translation: "métro", answer: "U-Bahnen", wrong: ["U-Bahns","U-Bahn","U-Bähnen"] },
  { singular: "Motorrad", article: "das", translation: "moto", answer: "Motorräder", wrong: ["Motorrads","Motorrade","Motorräden"] },
  { singular: "Koffer", article: "der", translation: "valise", answer: "Koffer", wrong: ["Koffern","Koffers","Köffer"] },
  { singular: "Stunde", article: "die", translation: "heure", answer: "Stunden", wrong: ["Stundes","Stunds","Stünden"] },
  { singular: "Minute", article: "die", translation: "minute", answer: "Minuten", wrong: ["Minutes","Minuts","Minutenn"] },
  { singular: "Tag", article: "der", translation: "jour", answer: "Tage", wrong: ["Tags","Tagen","Täge"] },
  { singular: "Woche", article: "die", translation: "semaine", answer: "Wochen", wrong: ["Woches","Wochs","Wöchen"] },
  { singular: "Monat", article: "der", translation: "mois", answer: "Monate", wrong: ["Monats","Monaten","Mönate"] },
  { singular: "Jahr", article: "das", translation: "année", answer: "Jahre", wrong: ["Jahrs","Jahren","Jähre"] },
  { singular: "Nacht", article: "die", translation: "nuit", answer: "Nächte", wrong: ["Nachts","Nachten","Nächten"] },
  { singular: "Morgen", article: "der", translation: "matin", answer: "Morgen", wrong: ["Morgens","Morgene","Mörgern"] },
  { singular: "Abend", article: "der", translation: "soir", answer: "Abende", wrong: ["Abends","Abenden","Äbende"] },
  { singular: "Beruf", article: "der", translation: "métier", answer: "Berufe", wrong: ["Berufs","Berufen","Berüfe"] },
  { singular: "Sprache", article: "die", translation: "langue", answer: "Sprachen", wrong: ["Spraches","Sprachs","Sprächen"] },
  { singular: "Wort", article: "das", translation: "mot", answer: "Wörter", wrong: ["Worts","Worte","Wörten"] },
  { singular: "Frage", article: "die", translation: "question", answer: "Fragen", wrong: ["Frages","Frags","Frägen"] },
  { singular: "Antwort", article: "die", translation: "réponse", answer: "Antworten", wrong: ["Antworts","Antworte","Antwörten"] },
  { singular: "Brief", article: "der", translation: "lettre (courrier)", answer: "Briefe", wrong: ["Briefs","Briefen","Briofe"] },
  { singular: "Zeitung", article: "die", translation: "journal (presse)", answer: "Zeitungen", wrong: ["Zeitungs","Zeitung","Zeitunge"] },
  { singular: "Heft", article: "das", translation: "cahier", answer: "Hefte", wrong: ["Hefts","Heften","Häfte"] },
  { singular: "Stift", article: "der", translation: "stylo / crayon", answer: "Stifte", wrong: ["Stifts","Stiften","Stüfte"] },
  { singular: "Tier", article: "das", translation: "animal", answer: "Tiere", wrong: ["Tiers","Tieren","Töere"] },
  { singular: "Vogel", article: "der", translation: "oiseau", answer: "Vögel", wrong: ["Vogels","Vogeln","Vögeln"] },
  { singular: "Pferd", article: "das", translation: "cheval", answer: "Pferde", wrong: ["Pferds","Pferden","Pferde"] },
  { singular: "Kuh", article: "die", translation: "vache", answer: "Kühe", wrong: ["Kuhs","Kuhen","Kue"] },
  { singular: "Schwein", article: "das", translation: "cochon", answer: "Schweine", wrong: ["Schweins","Schweinen","Schwöine"] },
  { singular: "Stern", article: "der", translation: "étoile", answer: "Sterne", wrong: ["Sterns","Sternen","Stärne"] },
  { singular: "Wolke", article: "die", translation: "nuage", answer: "Wolken", wrong: ["Wolkes","Wolks","Wölken"] },
  { singular: "Milch", article: "die", translation: "lait", answer: "invariant", wrong: ["Milche", "Milchs", "Milchen"] },
  { singular: "Geld", article: "das", translation: "argent", answer: "invariant", wrong: ["Gelder", "Geldee", "Gelde"] },
  { singular: "Schnee", article: "der", translation: "neige", answer: "invariant", wrong: ["Schnees", "Schneen", "Schnöe"] },
  { singular: "Regen", article: "der", translation: "pluie", answer: "invariant", wrong: ["Regens", "Regene", "Rögern"] },
  { singular: "Zucker", article: "der", translation: "sucre", answer: "invariant", wrong: ["Zuckers", "Zuckere", "Zücker"] },
  { singular: "Eis", article: "das", translation: "glace / neige", answer: "invariant", wrong: ["Eise", "Eisen", "Öeis"] },
  { singular: "Wind", article: "der", translation: "vent", answer: "invariant", wrong: ["Winde", "Winden", "Wünd"] },
  { singular: "Mond", article: "der", translation: "lune", answer: "invariant", wrong: ["Monde", "Monds", "Mönd"] },
  { singular: "Sonne", article: "die", translation: "soleil", answer: "invariant", wrong: ["Sonnen", "Sonnes", "Sönn"] },
];

export const VERB_TABLES: VerbTable[] = [
  { infinitive: 'sein',     translation: 'être',        forms: [{ pronoun: 'ich', answer: 'bin' }, { pronoun: 'du', answer: 'bist' }, { pronoun: 'er/sie/es', answer: 'ist' }, { pronoun: 'wir', answer: 'sind' }, { pronoun: 'ihr', answer: 'seid' }, { pronoun: 'sie/Sie', answer: 'sind' }] },
  { infinitive: 'haben',    translation: 'avoir',       forms: [{ pronoun: 'ich', answer: 'habe' }, { pronoun: 'du', answer: 'hast' }, { pronoun: 'er/sie/es', answer: 'hat' }, { pronoun: 'wir', answer: 'haben' }, { pronoun: 'ihr', answer: 'habt' }, { pronoun: 'sie/Sie', answer: 'haben' }] },
  { infinitive: 'werden',   translation: 'devenir',     forms: [{ pronoun: 'ich', answer: 'werde' }, { pronoun: 'du', answer: 'wirst' }, { pronoun: 'er/sie/es', answer: 'wird' }, { pronoun: 'wir', answer: 'werden' }, { pronoun: 'ihr', answer: 'werdet' }, { pronoun: 'sie/Sie', answer: 'werden' }] },
  { infinitive: 'wissen',   translation: 'savoir',      forms: [{ pronoun: 'ich', answer: 'weiß' }, { pronoun: 'du', answer: 'weißt' }, { pronoun: 'er/sie/es', answer: 'weiß' }, { pronoun: 'wir', answer: 'wissen' }, { pronoun: 'ihr', answer: 'wisst' }, { pronoun: 'sie/Sie', answer: 'wissen' }] },
  { infinitive: 'fahren',   translation: 'conduire',    forms: [{ pronoun: 'ich', answer: 'fahre' }, { pronoun: 'du', answer: 'fährst' }, { pronoun: 'er/sie/es', answer: 'fährt' }, { pronoun: 'wir', answer: 'fahren' }, { pronoun: 'ihr', answer: 'fahrt' }, { pronoun: 'sie/Sie', answer: 'fahren' }] },
  { infinitive: 'schlafen', translation: 'dormir',      forms: [{ pronoun: 'ich', answer: 'schlafe' }, { pronoun: 'du', answer: 'schläfst' }, { pronoun: 'er/sie/es', answer: 'schläft' }, { pronoun: 'wir', answer: 'schlafen' }, { pronoun: 'ihr', answer: 'schlaft' }, { pronoun: 'sie/Sie', answer: 'schlafen' }] },
  { infinitive: 'laufen',   translation: 'courir',      forms: [{ pronoun: 'ich', answer: 'laufe' }, { pronoun: 'du', answer: 'läufst' }, { pronoun: 'er/sie/es', answer: 'läuft' }, { pronoun: 'wir', answer: 'laufen' }, { pronoun: 'ihr', answer: 'lauft' }, { pronoun: 'sie/Sie', answer: 'laufen' }] },
  { infinitive: 'lesen',    translation: 'lire',        forms: [{ pronoun: 'ich', answer: 'lese' }, { pronoun: 'du', answer: 'liest' }, { pronoun: 'er/sie/es', answer: 'liest' }, { pronoun: 'wir', answer: 'lesen' }, { pronoun: 'ihr', answer: 'lest' }, { pronoun: 'sie/Sie', answer: 'lesen' }] },
  { infinitive: 'sehen',    translation: 'voir',        forms: [{ pronoun: 'ich', answer: 'sehe' }, { pronoun: 'du', answer: 'siehst' }, { pronoun: 'er/sie/es', answer: 'sieht' }, { pronoun: 'wir', answer: 'sehen' }, { pronoun: 'ihr', answer: 'seht' }, { pronoun: 'sie/Sie', answer: 'sehen' }] },
  { infinitive: 'nehmen',   translation: 'prendre',     forms: [{ pronoun: 'ich', answer: 'nehme' }, { pronoun: 'du', answer: 'nimmst' }, { pronoun: 'er/sie/es', answer: 'nimmt' }, { pronoun: 'wir', answer: 'nehmen' }, { pronoun: 'ihr', answer: 'nehmt' }, { pronoun: 'sie/Sie', answer: 'nehmen' }] },
  { infinitive: 'sprechen', translation: 'parler',      forms: [{ pronoun: 'ich', answer: 'spreche' }, { pronoun: 'du', answer: 'sprichst' }, { pronoun: 'er/sie/es', answer: 'spricht' }, { pronoun: 'wir', answer: 'sprechen' }, { pronoun: 'ihr', answer: 'sprecht' }, { pronoun: 'sie/Sie', answer: 'sprechen' }] },
  { infinitive: 'essen',    translation: 'manger',      forms: [{ pronoun: 'ich', answer: 'esse' }, { pronoun: 'du', answer: 'isst' }, { pronoun: 'er/sie/es', answer: 'isst' }, { pronoun: 'wir', answer: 'essen' }, { pronoun: 'ihr', answer: 'esst' }, { pronoun: 'sie/Sie', answer: 'essen' }] },
  { infinitive: 'geben',    translation: 'donner',      forms: [{ pronoun: 'ich', answer: 'gebe' }, { pronoun: 'du', answer: 'gibst' }, { pronoun: 'er/sie/es', answer: 'gibt' }, { pronoun: 'wir', answer: 'geben' }, { pronoun: 'ihr', answer: 'gebt' }, { pronoun: 'sie/Sie', answer: 'geben' }] },
  { infinitive: 'helfen',   translation: 'aider',       forms: [{ pronoun: 'ich', answer: 'helfe' }, { pronoun: 'du', answer: 'hilfst' }, { pronoun: 'er/sie/es', answer: 'hilft' }, { pronoun: 'wir', answer: 'helfen' }, { pronoun: 'ihr', answer: 'helft' }, { pronoun: 'sie/Sie', answer: 'helfen' }] },
  { infinitive: 'treffen',  translation: 'rencontrer',  forms: [{ pronoun: 'ich', answer: 'treffe' }, { pronoun: 'du', answer: 'triffst' }, { pronoun: 'er/sie/es', answer: 'trifft' }, { pronoun: 'wir', answer: 'treffen' }, { pronoun: 'ihr', answer: 'trefft' }, { pronoun: 'sie/Sie', answer: 'treffen' }] },
]

export const SECTIONS: Section[] = [
  { id: "articles", label: "Articles",         sub: "Der / Die / Das",          emoji: "🏷️", color: "#4A90E2", data: ARTICLES_DATA },
  { id: "countries", label: "Pays",            sub: "Articles des pays",         emoji: "🌍", color: "#9B59B6", data: COUNTRIES_DATA },
  { id: "verbs",    label: "Verbes irréguliers", sub: "Conjugaisons clés",       emoji: "⚡", color: "#E8407A", data: VERBS_DATA },
  { id: "plurals",  label: "Pluriels",          sub: "Règles et exceptions",     emoji: "✌️", color: "#27AE60", data: PLURALS_DATA },
];

export const ARTICLE_META: Record<string, ArticleMetaItem> = {
  "der":       { color: "#4A90E2", light: "#EBF4FF", border: "#B8D4F5", shadow: "#3070C2", label: "masculin / fém. datif" },
  "die":       { color: "#E8407A", light: "#FEE8F1", border: "#F5B8D0", shadow: "#C82060", label: "féminin" },
  "das":       { color: "#27AE60", light: "#E6F9EE", border: "#A8E8C4", shadow: "#1A8E45", label: "neutre" },
  "dem":       { color: "#D97706", light: "#FEF3C7", border: "#FCD34D", shadow: "#B45309", label: "masc./neutre datif" },
  "den":       { color: "#9B59B6", light: "#F3EAF9", border: "#D8B8F0", shadow: "#7B3996", label: "pluriel datif" },
  "die (pl.)": { color: "#9B59B6", light: "#F3EAF9", border: "#D8B8F0", shadow: "#7B3996", label: "pluriel" },
  "aucun":     { color: "#95A5A6", light: "#F2F4F4", border: "#D0D8D8", shadow: "#758586", label: "pas d'article" },
};

export const MSGS_OK   = ["Super ! 🎉","Parfait !","Bravo ! 💪","Exactement !","Oui !"];
export const MSGS_FAIL = ["Pas tout à fait…","Presque !","Attention !","Raté 😅"];

export const MAX_HEARTS = 5;
export const XP_CORRECT = 10;
export const XP_BONUS_COMPLETE = 50;
export const STORAGE_KEY = "deutsch-a1-stats";
export const WORD_STATS_KEY = "deutsch-a1-word-stats";

export const DEFAULT_STATS = {
  totalXP: 0,
  sessionStreak: 0,
  modules: {
    articles:  { answered: 0, correct: 0, bestStreak: 0, sessions: 0 },
    countries: { answered: 0, correct: 0, bestStreak: 0, sessions: 0 },
    verbs:     { answered: 0, correct: 0, bestStreak: 0, sessions: 0 },
    plurals:   { answered: 0, correct: 0, bestStreak: 0, sessions: 0 },
  },
};